MuhammadUsamaJahangir123/Skeleton

- ClassLibrary/ClassLibrary.csproj
- ClassLibrary/clsSupplier.cs
- Testing4/TestingSupplier.csproj
- Testing4/tstSupplier.cs
> Addded testing for Supplier Class

- ClassLibrary/clsSupplier.cs
- Testing4/tstSupplier.cs
The code is working fine, there are no issues that should affect the main branch
> Added attributes

- ClassLibrary/clsStaff.cs
- Output-Build.txt
- Testing1/tstStaff.cs
Added Attributes (Practical 7)
> Practical 7 DONE

- AdminSystem/CustomerDataEntry.aspx
- AdminSystem/CustomerDataEntry.aspx.cs
- AdminSystem/CustomerViewer.aspx
- AdminSystem/CustomerViewer.aspx.cs
- AdminSystem/OrderProcessingConfirmDelete.aspx
- AdminSystem/OrderProcessingViewer.aspx
- AdminSystem/StaffViewer.aspx
- Skeleton.sln
I have checked for any conflict there are none.
> Made a form with 2 pages working with 0 errors and showing data correctly.

- Testing5/tstStock.cs
> Added Testing for Stock Class

- ClassLibrary/clsStaff.cs
- Testing1/tstStaff.cs
Created FindMethod  and tests.
All the tests pass
> Practical 9a Done

- ClassLibrary/clsCustomer.cs
- Testing2/tstCustomer.cs
No errors have occurred during the tests.
> Created Find Method and Tested them No errors

- AdminSystem/StaffDataEntry.aspx
- AdminSystem/StaffDataEntry.aspx.cs
- AdminSystem/StaffViewer.aspx.cs
- ClassLibrary/clsStaff.cs
- SQLQuery2.sql
- Testing1/tstStaff.cs
- dbo.sproc_tbStaff_FilterByStaffID.sql
- dbo.tbStaff.sql
Tested and everything is working fine
> Finally finished Lab 9b

- ClassLibrary/clsSupplier.cs
- Testing4/tstSupplier.cs
> Debug Lab 9a complete

- ClassLibrary/clsCustomer.cs
- Testing2/tstCustomer.cs
Lab 10 Valid Method and Tests Completed
> Made Valid Method with tests which all passed

- ClassLibrary/clsStaff.cs
- Testing1/tstStaff.cs
All checked and everything works flawlessly
> Finally finished lab10 (Kushal)

- AdminSystem/CustomerDataEntry.aspx.cs
- ClassLibrary/clsCustomer.cs
- Output-Build.txt
Validation on the web form with correct errors when left blank.
> Validation Method and Tests work with web form displaying correct errors

- AdminSystem/SupplierDataEntry.aspx
> SORRY GUYS I FIXED IT

- AdminSystem/StaffDataEntry.aspx.cs
- Testing1/tstStaff.cs
Tested it and it works perfectly
> Done Lab11 (Kushal Dilip)

- AdminSystem/StaffList.aspx
- AdminSystem/StaffList.aspx.cs
- ClassLibrary/ClassLibrary.csproj
- ClassLibrary/clsStaffCollection.cs
- Testing1/TestingStaff.csproj
- Testing1/tstStaffCollection.cs
I could not test it the application because of mistakes on Stock Component that is providing build errors.
The code is all good so it should work fine though
> Done with lab12 (Kushal Dilip)

- AdminSystem/StockDataEntry.aspx
- AdminSystem/StockDataEntry.aspx.cs
- AdminSystem/StockViewer.aspx.cs
- ClassLibrary/ClassLibrary.csproj
- ClassLibrary/clsStock.cs
- Testing5/TestingStock.csproj
- Testing5/tstStock.cs
> No errors finally

- AdminSystem/StaffList.aspx
- AdminSystem/StaffList.aspx.cs
- ClassLibrary/clsStaffCollection.cs
- Testing1/tstStaffCollection.cs
- dbo.Procedure.sql
> Did Lab 13A up until page 8, continuing the rest from home

- AdminSystem/CustomerDataEntry.aspx.cs
- AdminSystem/CustomerList.aspx
- AdminSystem/CustomerList.aspx.cs
- ClassLibrary/clsCustomerCollection.cs
- Testing2/tstCustomerCollection.cs
Test run fine but doesn't let me run on the browser when trying to test the update method.
> Update method done but has 1 issue

- ClassLibrary/clsStock.cs
- Testing5/tstStock.cs
catching up - no errors so far.
> catching up - no errors so far.

- AdminSystem/StaffDataEntry.aspx.cs
- AdminSystem/StaffList.aspx.cs
- ClassLibrary/clsStaff.cs
It's working and all the tests pass.
> Finished lab 13A (Kushal)

- AdminSystem/StaffDataEntry.aspx.cs
- AdminSystem/StaffList.aspx
- AdminSystem/StaffList.aspx.cs
- ClassLibrary/clsStaffCollection.cs
- Testing1/tstStaffCollection.cs
> Lab 13B not finished, but it works (No Errors)

- ClassLibrary/clsStock.cs
- Testing5/tstStock.cs
> catching up - no errors

- AdminSystem/OrderProcessingViewer.aspx.cs
- AdminSystem/StaffDataEntry.aspx.cs
It's working and the tests pass.
I commented out the lines (20, 21 and 22) on OrderProcessingViewer.aspx.cs as they were giving build errors
> Finished lab 13B (Kushal)

- Testing5/tstStock.cs
> catching up

- AdminSystem/CustomerConfirmDelete.aspx
- AdminSystem/CustomerConfirmDelete.aspx.cs
- AdminSystem/CustomerList.aspx
- AdminSystem/CustomerList.aspx.cs
- ClassLibrary/clsCustomerCollection.cs
- Testing2/tstCustomerCollection.cs
> Lab13 and 14 Done

- AdminSystem/StaffConfirmDelete.aspx
- AdminSystem/StaffConfirmDelete.aspx.cs
- AdminSystem/StaffList.aspx
- AdminSystem/StaffList.aspx.cs
- ClassLibrary/clsStaffCollection.cs
- Testing1/tstStaffCollection.cs
All Tested and everything works absolutely flawless
> Finished up to lab 14B (Kushal)

- AdminSystem/CustomerLogin.aspx
- AdminSystem/CustomerLogin.aspx.cs
- ClassLibrary/ClassLibrary.csproj
- ClassLibrary/clsCustomerUser.cs
- Output-Build.txt
- Testing2/TestingCustomer.csproj
- Testing2/tstCustomerCollection.cs
- Testing2/tstCustomerUser.cs
Lab 15 0 Errors Login Page Done
> Done Lab 15

- AdminSystem/CustomerDataEntry.aspx
- AdminSystem/CustomerDataEntry.aspx.cs
- AdminSystem/CustomerList.aspx
- AdminSystem/CustomerList.aspx.cs
- AdminSystem/CustomerLogin.aspx
- AdminSystem/CustomerLogin.aspx.cs
- AdminSystem/TeamMainMenu.aspx
- AdminSystem/TeamMainMenu.aspx.cs
> Lab 16 Finished

- ClassLibrary/clsStock.cs
- Testing5/tstStock.cs
> parameters - no errors

- ClassLibrary/clsStock.cs
- Testing5/tstStock.cs
> fixed error soz

- AdminSystem/StaffList.aspx
> All done FR (Kushal#)

- AdminSystem/CustomerDataEntry.aspx
- AdminSystem/CustomerDataEntry.aspx.cs
> Button Fixed Flawless

- ClassLibrary/clsStockCollection.cs
- Testing5/tstStockCollection.cs
> almost there

- AdminSystem/StockList.aspx
- AdminSystem/StockList.aspx.cs
> display - no errors

- AdminSystem/StockDataEntry.aspx
- AdminSystem/StockDataEntry.aspx.cs
- AdminSystem/StockList.aspx
- AdminSystem/StockList.aspx.cs
- ClassLibrary/clsStockCollection.cs
- Testing5/tstStockCollection.cs
have an error, will fix before practical
> 2 am correcting an error

- AdminSystem/StockDataEntry.aspx.cs
> fixed errors

- AdminSystem/StockConfirmDelete.aspx
- AdminSystem/StockConfirmDelete.aspx.cs
- AdminSystem/StockList.aspx
- AdminSystem/StockList.aspx.cs
- ClassLibrary/ClassLibrary.csproj
- ClassLibrary/clsStockCollection.cs
- ClassLibrary/clsStockUser.cs
- Testing5/TestingStock.csproj
- Testing5/tstStockCollection.cs
- Testing5/tstStockUser.cs
> due to finish today - no errors

- AdminSystem/StockDataEntry.aspx
- AdminSystem/StockDataEntry.aspx.cs
- AdminSystem/StockList.aspx
- AdminSystem/StockList.aspx.cs
- AdminSystem/StockLogin.aspx
- AdminSystem/StockLogin.aspx.cs
- AdminSystem/TeamMainMenu.aspx
- AdminSystem/TeamMainMenu.aspx.cs
- ClassLibrary/clsStockUser.cs
- Testing5/tstStockUser.cs
> Finished no errors

- ClassLibrary/clsCustomer.cs
- ClassLibrary/clsCustomerCollection.cs
- Testing2/tstCustomer.cs
- Testing2/tstCustomerCollection.cs
Made Some Fixes to Error Messages
> Made Some Tweaks to Error Messages

- AdminSystem/StaffList.aspx
- ClassLibrary/clsStaff.cs
- Testing1/tstStaff.cs
- Testing1/tstStaffCollection.cs
> fixed the errors

- AdminSystem/CustomerDataEntry.aspx.cs
> Removed a Useless Feature

- AdminSystem/CustomerList.aspx.cs
> New usama branch
